package com.jcrawleydev.gemsdrop.audio;

public enum SoundEffect {
    GEMS_DISAPPEAR,
    GEMS_DISAPPEAR_CHAIN_REACTION_1,
    GEMS_DISAPPEAR_CHAIN_REACTION_2,
    GEMS_DISAPPEAR_CHAIN_REACTION_3,
    GEMS_DISAPPEAR_CHAIN_REACTION_4,
    GEMS_DISAPPEAR_CHAIN_REACTION_5,
    GEMS_DISAPPEAR_CHAIN_REACTION_6,
    GEMS_DISAPPEAR_CHAIN_REACTION_7,
    GEMS_DISAPPEAR_SPECIAL,
    WONDER_GEM_GEMS_DISAPPEAR,
    WONDER_GEM_HITS_FLOOR,
    GEM_HITS_FLOOR,
    GEM_HITS_GEM,
    GEMS_GREYED_OUT,
    MENU_BUTTON }